Add some configure/CMake options for enabling/disabling Subzero targets.
Mirrors the LLVM_TARGETS_TO_BUILD, but kept separate since
(a) the spellings are different
(b) we may keep X8632 separate from X8664 unlike LLVM

This setups up an xmacro file to enumerate the enabled targets.

NaCl change:
https://codereview.chromium.org/1082953002/

Subzero change:
https://codereview.chromium.org/1075363002/

This change has to be atomic w/ the NaCl change since the
default is "none" which blows up.

An alternative may be to move the header to Subzero, and
"configure" stuff via -D in the CXXFLAGS, filling in the
.def file that way if possible.

BUG= https://code.google.com/p/nativeclient/issues/detail?id=4076
R=stichnot@chromium.org

Review URL: https://codereview.chromium.org/1084753002

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -718,6 +718,7 @@ LLVM_ENUM_TARGETS
 LLVM_ENUM_ASM_PRINTERS
 LLVM_ENUM_ASM_PARSERS
 LLVM_ENUM_DISASSEMBLERS
+SUBZERO_ENUM_TARGETS
 OPTIMIZE_OPTION
 EXTRA_OPTIONS
 EXTRA_LD_OPTIONS
@@ -1435,11 +1436,14 @@ Optional Features:
   --enable-targets        Build specific host targets: all or
                           target1,target2,... Valid targets are: host, x86,
                           x86_64, sparc, powerpc, arm64, arm, aarch64, mips,
-                          hexagon, xcore, msp430, nvptx, systemz, r600, and
-                          js, cpp (default=all)
+                          hexagon, xcore, msp430, nvptx, systemz, r600, js,
+                          and cpp (default=all)
   --enable-experimental-targets
                           Build experimental host targets: disable or
                           target1,target2,... (default=disable)
+  --enable-subzero-targets
+                          Build specific subzero targets:
+                          target1,target2,...(default=none)
   --enable-bindings       Build specific language bindings:
                           all,auto,none,{binding-name} (default=auto)
   --enable-terminfo       Query the terminfo database if available (default is
@@ -5314,7 +5318,7 @@ _ACEOF
 
 fi
 
-ALL_TARGETS="X86 Sparc PowerPC ARM AArch64 Mips XCore MSP430 CppBackend NVPTX Hexagon SystemZ R600"
+ALL_TARGETS="X86 Sparc PowerPC ARM AArch64 Mips XCore MSP430 CppBackend JSBackend NVPTX Hexagon SystemZ R600"
 ALL_TARGETS=$ALL_TARGETS
 
 
@@ -5466,6 +5470,37 @@ done
 
 
 
+
+
+
+SUBZERO_TARGETS_TO_BUILD=""
+# Check whether --enable-subzero_targets was given.
+if test "${enable_subzero_targets+set}" = set; then
+  enableval=$enable_subzero_targets;
+else
+  enableval=none
+fi
+
+case "$enableval" in
+  none) ;;
+  *)for a_target in `echo $enableval|sed -e 's/,/ /g' ` ; do
+      case "$a_target" in
+        X8632)  SUBZERO_TARGETS_TO_BUILD="X8632 $SUBZERO_TARGETS_TO_BUILD" ;;
+        X8664)  SUBZERO_TARGETS_TO_BUILD="X8664 $SUBZERO_TARGETS_TO_BUILD" ;;
+        ARM32)  SUBZERO_TARGETS_TO_BUILD="ARM32 $SUBZERO_TARGETS_TO_BUILD" ;;
+        ARM64)  SUBZERO_TARGETS_TO_BUILD="ARM64 $SUBZERO_TARGETS_TO_BUILD" ;;
+        *) { { echo "$as_me:$LINENO: error: Unrecognized subzero target $a_target" >&5
+echo "$as_me: error: Unrecognized subzero target $a_target" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+  done
+  ;;
+esac
+
+SUBZERO_ENUM_TARGETS=""
+for target_to_build in $SUBZERO_TARGETS_TO_BUILD; do
+  SUBZERO_ENUM_TARGETS="SUBZERO_TARGET($target_to_build) $SUBZERO_ENUM_TARGETS"
+done
 
 
 
@@ -18440,6 +18475,8 @@ ac_config_headers="$ac_config_headers include/llvm/Config/config.h include/llvm/
 
 
 
+ac_config_files="$ac_config_files include/llvm/Config/SZTargets.def"
+
 ac_config_files="$ac_config_files include/llvm/Config/Targets.def"
 
 ac_config_files="$ac_config_files include/llvm/Config/AsmPrinters.def"
@@ -19069,6 +19106,7 @@ do
   case $ac_config_target in
     "include/llvm/Config/config.h") CONFIG_HEADERS="$CONFIG_HEADERS include/llvm/Config/config.h" ;;
     "include/llvm/Config/llvm-config.h") CONFIG_HEADERS="$CONFIG_HEADERS include/llvm/Config/llvm-config.h" ;;
+    "include/llvm/Config/SZTargets.def") CONFIG_FILES="$CONFIG_FILES include/llvm/Config/SZTargets.def" ;;
     "include/llvm/Config/Targets.def") CONFIG_FILES="$CONFIG_FILES include/llvm/Config/Targets.def" ;;
     "include/llvm/Config/AsmPrinters.def") CONFIG_FILES="$CONFIG_FILES include/llvm/Config/AsmPrinters.def" ;;
     "include/llvm/Config/AsmParsers.def") CONFIG_FILES="$CONFIG_FILES include/llvm/Config/AsmParsers.def" ;;
@@ -19312,6 +19350,7 @@ LLVM_ENUM_TARGETS!$LLVM_ENUM_TARGETS$ac_delim
 LLVM_ENUM_ASM_PRINTERS!$LLVM_ENUM_ASM_PRINTERS$ac_delim
 LLVM_ENUM_ASM_PARSERS!$LLVM_ENUM_ASM_PARSERS$ac_delim
 LLVM_ENUM_DISASSEMBLERS!$LLVM_ENUM_DISASSEMBLERS$ac_delim
+SUBZERO_ENUM_TARGETS!$SUBZERO_ENUM_TARGETS$ac_delim
 OPTIMIZE_OPTION!$OPTIMIZE_OPTION$ac_delim
 EXTRA_OPTIONS!$EXTRA_OPTIONS$ac_delim
 EXTRA_LD_OPTIONS!$EXTRA_LD_OPTIONS$ac_delim
@@ -19391,7 +19430,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 96; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
